AWSTemplateFormatVersion: '2010-09-09'
Description: >
  External ALB to expose Methode servlets to the internet
Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: Security Groups to attach load balancer
    Default: sg-e1875c99,sg-eae09d91
  SubnetIds:
    Type: CommaDelimitedList
    Description: Public subnets to attach load balancer
    Default: subnet-cbbc0d82,subnet-3f3fcb64,subnet-a467cfc3
  VpcId:
    Type: String
    Description: >
      Optional - Specifies the ID of an existing VPC in which to launch
      your container instances.
    Default: vpc-729f2815
    AllowedPattern: "^(?:vpc-[0-9a-f]{8}|)$"
    ConstraintDescription: >
      VPC Id must begin with 'vpc-'
  TagDescription:
    Description: Tag detail for the Description
    Type: String
    Default: External ALB for Methode servlets
  TagTeamDL:
    Description: Tag detail for the TeamDL
    ConstraintDescription: There must be a valid email address for the TeamDL Topic
    Type: String
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    Default: team.cms@ft.com
  TagSystemCode:
      Description: SystemCode
      Type: String
      Default: methode
  TagEnvironment:
    Description: Tag detail for the Environment
    Type: String
    Default: int
    AllowedValues:
      - 't'
      - 'p'
      - 'int'
Mappings:
  EnvMap:
    t:
      env: "test"
    p:
      env: "prod"
    int:
      env: "int"
Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
     Name: !Sub "${AWS::StackName}"
     Type: application
     Scheme: internet-facing
     Subnets: !Ref SubnetIds
     SecurityGroups: !Ref SecurityGroupIds
     Tags:
       -
         Key: Name
         Value: !Sub "CMS-${AWS::StackName}"
       -
         Key: Description
         Value:
           Ref: TagDescription
       -
         Key: environment
         Value:
           Ref: TagEnvironment
       - Key: teamDL
         Value:
           Ref: TagTeamDL
       - Key: systemCode
         Value:
           Ref: TagSystemCode
  TargetGroupAdOrder:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
     Name: !Sub "${AWS::StackName}-adorder"
     Port: 80
     Protocol: HTTP
     HealthCheckPath: /adorder/__health
     HealthCheckProtocol: HTTP
     HealthCheckIntervalSeconds: 10
     HealthCheckTimeoutSeconds: 5
     HealthyThresholdCount: 2
     UnhealthyThresholdCount: 2
     Matcher:
       HttpCode: '200'
     TargetGroupAttributes:
     - Key: deregistration_delay.timeout_seconds
       Value: '60'
     - Key: stickiness.enabled
       Value: true
     - Key: stickiness.lb_cookie.duration_seconds
       Value: 86400
     VpcId: !Ref VpcId
  ListenerRuleAdOrder:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Ref: TargetGroupAdOrder
      Conditions:
      - Field: path-pattern
        Values:
        - "/adorder*"
      ListenerArn:
        Ref: ListenerHTTPS
      Priority: 10
  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: TargetGroupAdOrder
      LoadBalancerArn:
        Ref: ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:eu-west-1:307921801440:certificate/00b98d3d-2c61-4a52-a28c-5bbb79c04011      
Outputs:
  LoadBalancerDNSName:
    Description: Load Balancer DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
